import { Body, Controller, Get, Header, HttpCode, HttpStatus, Patch, Response } from '@nestjs/common';
import { AdminService } from './admin.service';
import { AppException, ERROR_CODE } from '../exceptions';
import { ApiCreatedResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { ApiAppErrorResponse } from '../app.dto';
import { ConfigModule } from '../config/config.module';
import ConfigurationReqDto from './dto/req/configure-req.dto';
import { ReportPropertyType, UserType } from '@prisma/client';
import { Response as ExpressResponse } from 'express';
import { GetUser } from 'src/auth/decorator';
import { User } from 'src/user/interfaces/user.interface';

@Controller('admin')
@ApiTags('Authentication')
export class AdminController {
  constructor(
    private admin: AdminService,
    private config: ConfigModule,
  ) {}

  @HttpCode(HttpStatus.NO_CONTENT)
  @Patch('config')
  @ApiOperation({
    description: 'Edits report variables',
  })
  async editConfiguration(@Body() dto: ConfigurationReqDto, @GetUser() user: User) {
    if (user.type !== UserType.ADMIN) throw new AppException(ERROR_CODE.FORBIDDEN_NOT_ENOUGH_PERMISSIONS, 'ADMIN');
    if (Object.keys(dto).length === 0) throw new AppException(ERROR_CODE.PARAM_EMPTY_BODY);
    if (!this.config.CRYPTO_PUBLIC_KEY) throw new AppException(ERROR_CODE.MISSING_ENV, 'CRYPTO_PUBLIC_KEY');
    return this.admin.setConfiguration(dto);
  }

  @Get('config')
  async getConfigurationState(@GetUser() user: User) {
    if (user.type !== UserType.ADMIN) throw new AppException(ERROR_CODE.FORBIDDEN_NOT_ENOUGH_PERMISSIONS, 'ADMIN');
    return this.admin.getConfigurationSummary();
  }

  @HttpCode(HttpStatus.CREATED)
  @Get('report')
  @ApiOperation({
    description: 'Returns a report of all new entries since the last report was generated.',
  })
  @ApiCreatedResponse({
    description: 'The XML report is returned.',
  })
  @ApiAppErrorResponse(
    ERROR_CODE.INVALID_TOKEN_FORMAT,
    'The token is not in the right format. This may happen if you did not use the syntax `Bearer {token there}`, or the token was not generated by the API',
  )
  async generateReport(@Response() res: ExpressResponse, @GetUser() user: User) {
    if (user.type !== UserType.ADMIN) throw new AppException(ERROR_CODE.FORBIDDEN_NOT_ENOUGH_PERMISSIONS, 'ADMIN');
    const users = await this.admin.getUsersReport();
    if (users.length === 0) throw new AppException(ERROR_CODE.EMPTY_REPORT);
    const configuration = await this.admin.getConfiguration();
    if (Object.keys(configuration).length < Object.keys(ReportPropertyType).length)
      throw new AppException(ERROR_CODE.MISSING_CONFIG);
    const ctrlSum = users.reduce((sum, user) => sum + Math.min(10000, user.balance), 0) / 100;
    res.setHeader('Content-Type', 'application/xml');
    res.send(
      this.toXML({
        Document: {
          xmlns: 'urn:iso:std:iso:20022:tech:xsd:pain.001.001.12',
          'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
          CstmrCdtTrfInitn: {
            GrpHdr: {
              MsgId: { value: `BUCKUTT-${Date.now()}`.slice(0, 35) },
              CreDtTm: { value: new Date().toISOString().slice(0, -5) },
              NbOfTxs: { value: users.length },
              CtrlSum: { value: ctrlSum },
              InitgPty: {
                Nm: { value: configuration.REPORT_DEBTOR_NAME },
              },
            },
            PmtInf: [
              {
                PmtInfId: { value: `BUCKUTT-P1-${Date.now()}`.slice(0, 35) },
                PmtMtd: { value: 'TRF' },
                BtchBookg: { value: false }, // Set to true to display only one entry in the bank
                NbOfTxs: { value: users.length },
                CtrlSum: { value: ctrlSum },
                PmtTpInf: {
                  InstrPrty: { value: 'NORM' },
                  SvcLvl: {
                    Cd: { value: 'SEPA' },
                  },
                  CtgyPurp: {
                    Cd: { value: 'IDCP' }, // Transaction is reimbursement of debit card payment.
                  },
                },
                ReqdExctnDt: { DtTm: { value: new Date().toISOString().slice(0, -5) } },
                Dbtr: {
                  Nm: { value: configuration.REPORT_DEBTOR_NAME },
                  PstlAdr: {
                    Ctry: { value: 'FR' },
                    AdrLine: [configuration.REPORT_DEBTOR_ADDR, configuration.REPORT_DEBTOR_ADDR2].map((v) => ({
                      value: v,
                    })),
                  },
                },
                DbtrAcct: {
                  Id: {
                    IBAN: { value: configuration.REPORT_DEBTOR_IBAN },
                  },
                },
                DbtrAgt: {
                  FinInstnId: {
                    BICFI: { value: configuration.REPORT_DEBTOR_BIC },
                  },
                },
                ChrgBr: { value: 'SLEV' },
                CdtTrfTxInf: users.map((user) => ({
                  PmtId: {
                    EndToEndId: { value: `buckutt-user-${user.id}`.slice(0, 35) },
                  },
                  Amt: {
                    InstdAmt: {
                      value: Math.min(100, user.balance / 100),
                      Ccy: 'EUR',
                    },
                  },
                  CdtrAgt: {
                    FinInstnId: {
                      BICFI: { value: 'TOBIC' },
                    },
                  },
                  Cdtr: {
                    Nm: { value: sanitize(`${user.firstName} ${user.lastName.toUpperCase()}`).slice(0, 140) },
                  },
                  CdtrAcct: {
                    Id: {
                      IBAN: { value: user.iban },
                    },
                  },
                  RmtInf: {
                    Ustrd: {
                      value: 'Remboursement BuckUTT'.slice(0, 140),
                    },
                  },
                })),
              },
            ],
          },
        },
      }),
    );
  }

  private toXML(data: XMLObject, head: string = null) {
    const contents = Object.entries(data);
    const props = contents.filter(isProp);
    const objects = contents.filter(isChild);
    const serializedProps = props.length ? ' ' + props.map(([k, v]) => `${k}="${v}"`).join(' ') : '';
    const serializedObjects = `${objects
      .map(([k, v]) =>
        k === 'value' ? v : v instanceof Array ? v.map((v2) => this.toXML(v2, k)).join('') : this.toXML(v, k),
      )
      .join('')}`;
    return !head
      ? `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>${serializedObjects}`
      : serializedObjects.length
        ? `<${head}${serializedProps}>${serializedObjects}</${head}>`
        : `<${head}${serializedProps}/>`;
  }
}

type XMLObject = { [key in string]: XMLParsable | XMLObject | Array<XMLObject> } & { value?: XMLParsable };
type XMLParsable = string | number | boolean;

function isProp(
  props: [string, XMLObject | XMLParsable | Array<XMLObject>],
): props is [key: string, value: XMLParsable] {
  return !isChild(props);
}
function isChild(
  props: [string, XMLObject | XMLParsable | Array<XMLObject>],
): props is [key: string, value: XMLObject | Array<XMLObject>] {
  return props[0] === 'value' || ((props[1] instanceof Array || typeof props[1] === 'object') && props[1] !== null);
}

function sanitize(str: string) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}
