import { Controller, Get, Header, Headers, HttpCode, HttpStatus, Post } from '@nestjs/common';
import { AdminService } from './admin.service';
import { IsPublic } from '../auth/decorator/public.decorator';
import { ERROR_CODE } from '../exceptions';
import { ApiCreatedResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { ApiAppErrorResponse } from '../app.dto';

@Controller('admin')
@ApiTags('Authentication')
export class AdminController {
  constructor(private admin: AdminService) {}

  @HttpCode(HttpStatus.CREATED)
  @IsPublic()
  @Get('report')
  @Header('content-type', 'application/xml')
  @ApiOperation({
    description: 'Returns a report of all new entries since the last report was generated.',
  })
  @ApiCreatedResponse({
    description: 'The XML report is returned.',
  })
  @ApiAppErrorResponse(
    ERROR_CODE.INVALID_TOKEN_FORMAT,
    'The token is not in the right format. This may happen if you did not use the syntax `Bearer {token there}`, or the token was not generated by the API',
  )
  async generateReport(@Headers() headers: Record<string, string>) {
    // this.admin.getUsersReport();
    return this.toXML({
      Document: {
        xmlns: 'urn:iso:std:iso:20022:tech:xsd:pain.001.001.12',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        CstmrCdtTrfInitn: {
          GrpHdr: {
            MsgId: { value: '0'.slice(0, 35) },
            CreDtTm: { value: new Date().toISOString().slice(0, -5) },
            NbOfTxs: { value: 0 },
            CtrlSum: { value: 0 },
            InitgPty: {
              Nm: { value: 'Company Name'.slice(0, 140) },
              Id: { PrvtId: { Othr: { Id: { value: 'Company ID'.slice(0, 256) } } } },
            },
          },
          PmtInf: [
            {
              PmtInfId: { value: '0'.slice(0, 35) },
              PmtMtd: { value: 'TRF' },
              BtchBookg: { value: false }, // Set to true to display only one entry in the bank
              NbOfTxs: { value: 0 },
              CtrlSum: { value: 0 },
              PmtTpInf: {
                InstrPrty: { value: 'NORM' },
                SvcLvl: {
                  Cd: { value: 'SEPA' },
                },
                CtgyPurp: {
                  Cd: { value: 'IDCP' }, // Transaction is reimbursement of debit card payment.
                },
              },
              ReqdExctnDt: { DtTm: { value: new Date().toISOString().slice(0, -5) } },
              Dbtr: {
                Nm: { value: 'Company Name'.slice(0, 140) },
                PstlAdr: {
                  Ctry: { value: 'FR' },
                },
              },
              DbtrAcct: {
                Id: {
                  IBAN: { value: 'FROMIBAN' },
                },
              },
              DbtrAgt: {
                FinInstnId: {
                  BICFI: { value: 'FROMBIC' },
                },
              },
              ChrgBr: { value: 'SLEV' },
              CdtTrfTxInf: [
                {
                  PmtId: {
                    EndToEndId: { value: '0'.slice(0, 35) },
                  },
                  Amt: {
                    InstdAmt: {
                      value: 0,
                      Ccy: 'EUR',
                    },
                  },
                  CdtrAgt: {
                    FinInstnId: {
                      BICFI: { value: 'TOBIC' },
                    },
                  },
                  Cdtr: {
                    Nm: { value: 'User Name'.slice(0, 140) },
                  },
                  CdtrAcct: {
                    Id: {
                      IBAN: { value: 'TOIBAN' },
                    },
                  },
                  RmtInf: {
                    Ustrd: {
                      value: 'Transaction description'.slice(0, 140),
                    },
                  },
                },
              ],
            },
          ],
        },
      },
    });
  }

  private toXML(data: XMLObject, head: string = null) {
    const contents = Object.entries(data);
    const props = contents.filter(isProp);
    const objects = contents.filter(isChild);
    const serializedProps = props.length ? ' ' + props.map(([k, v]) => `${k}="${v}"`).join(' ') : '';
    const serializedObjects = `${objects
      .map(([k, v]) =>
        k === 'value' ? v : v instanceof Array ? v.map((v2) => this.toXML(v2, k)).join('') : this.toXML(v, k),
      )
      .join('')}`;
    return !head
      ? `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>${serializedObjects}`
      : serializedObjects.length
      ? `<${head}${serializedProps}>${serializedObjects}</${head}>`
      : `<${head}${serializedProps}/>`;
  }
}

type XMLObject = { [key in string]: XMLParsable | XMLObject | Array<XMLObject> } & { value?: XMLParsable };
type XMLParsable = string | number | boolean;

function isProp(
  props: [string, XMLObject | XMLParsable | Array<XMLObject>],
): props is [key: string, value: XMLParsable] {
  return !isChild(props);
}
function isChild(
  props: [string, XMLObject | XMLParsable | Array<XMLObject>],
): props is [key: string, value: XMLObject | Array<XMLObject>] {
  return props[0] === 'value' || ((props[1] instanceof Array || typeof props[1] === 'object') && props[1] !== null);
}
