import { Controller, Get, Header, Headers, HttpCode, HttpStatus, Post } from '@nestjs/common';
import { AdminService } from './admin.service';
import { IsPublic } from '../auth/decorator/public.decorator';
import { ERROR_CODE } from '../exceptions';
import { ApiCreatedResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { ApiAppErrorResponse } from '../app.dto';
import { ConfigModule } from '../config/config.module';

@Controller('admin')
@ApiTags('Authentication')
export class AdminController {
  constructor(
    private admin: AdminService,
    private config: ConfigModule,
  ) {}

  @HttpCode(HttpStatus.CREATED)
  @IsPublic()
  @Get('report')
  @Header('content-type', 'application/xml')
  @ApiOperation({
    description: 'Returns a report of all new entries since the last report was generated.',
  })
  @ApiCreatedResponse({
    description: 'The XML report is returned.',
  })
  @ApiAppErrorResponse(
    ERROR_CODE.INVALID_TOKEN_FORMAT,
    'The token is not in the right format. This may happen if you did not use the syntax `Bearer {token there}`, or the token was not generated by the API',
  )
  async generateReport() {
    const users = await this.admin.getUsersReport();
    const ctrlSum = users.reduce((sum, user) => sum + Math.min(10000, user.balance), 0) / 100;
    return this.toXML({
      Document: {
        xmlns: 'urn:iso:std:iso:20022:tech:xsd:pain.001.001.12',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        CstmrCdtTrfInitn: {
          GrpHdr: {
            MsgId: { value: `BUCKUTT-${Date.now()}`.slice(0, 35) },
            CreDtTm: { value: new Date().toISOString().slice(0, -5) },
            NbOfTxs: { value: users.length },
            CtrlSum: { value: ctrlSum },
            InitgPty: {
              Nm: { value: this.config.XML_EXPORT_COMPANY_NAME.slice(0, 140) },
            },
          },
          PmtInf: [
            {
              PmtInfId: { value: `BUCKUTT-P1-${Date.now()}`.slice(0, 35) },
              PmtMtd: { value: 'TRF' },
              BtchBookg: { value: false }, // Set to true to display only one entry in the bank
              NbOfTxs: { value: users.length },
              CtrlSum: { value: ctrlSum },
              PmtTpInf: {
                InstrPrty: { value: 'NORM' },
                SvcLvl: {
                  Cd: { value: 'SEPA' },
                },
                CtgyPurp: {
                  Cd: { value: 'IDCP' }, // Transaction is reimbursement of debit card payment.
                },
              },
              ReqdExctnDt: { DtTm: { value: new Date().toISOString().slice(0, -5) } },
              Dbtr: {
                Nm: { value: this.config.XML_EXPORT_COMPANY_NAME.slice(0, 140) },
                PstlAdr: {
                  Ctry: { value: 'FR' },
                  AdrLine: [
                    this.config.XML_EXPORT_COMPANY_ADDRESS.slice(0, 70),
                    this.config.XML_EXPORT_COMPANY_ADDRESS_2.slice(0, 70),
                  ].map((v) => ({ value: v })),
                },
              },
              DbtrAcct: {
                Id: {
                  IBAN: { value: this.config.XML_EXPORT_COMPANY_IBAN },
                },
              },
              DbtrAgt: {
                FinInstnId: {
                  BICFI: { value: this.config.XML_EXPORT_COMPANY_BIC },
                },
              },
              ChrgBr: { value: 'SLEV' },
              CdtTrfTxInf: users.map((user) => ({
                PmtId: {
                  EndToEndId: { value: `buckutt-user-${user.id}`.slice(0, 35) },
                },
                Amt: {
                  InstdAmt: {
                    value: Math.min(100, user.balance / 100),
                    Ccy: 'EUR',
                  },
                },
                CdtrAgt: {
                  FinInstnId: {
                    BICFI: { value: 'TOBIC' },
                  },
                },
                Cdtr: {
                  Nm: { value: sanitize(`${user.firstName} ${user.lastName.toUpperCase()}`).slice(0, 140) },
                },
                CdtrAcct: {
                  Id: {
                    IBAN: { value: user.iban },
                  },
                },
                RmtInf: {
                  Ustrd: {
                    value: 'Remboursement BuckUTT'.slice(0, 140),
                  },
                },
              })),
            },
          ],
        },
      },
    });
  }

  private toXML(data: XMLObject, head: string = null) {
    const contents = Object.entries(data);
    const props = contents.filter(isProp);
    const objects = contents.filter(isChild);
    const serializedProps = props.length ? ' ' + props.map(([k, v]) => `${k}="${v}"`).join(' ') : '';
    const serializedObjects = `${objects
      .map(([k, v]) =>
        k === 'value' ? v : v instanceof Array ? v.map((v2) => this.toXML(v2, k)).join('') : this.toXML(v, k),
      )
      .join('')}`;
    return !head
      ? `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>${serializedObjects}`
      : serializedObjects.length
        ? `<${head}${serializedProps}>${serializedObjects}</${head}>`
        : `<${head}${serializedProps}/>`;
  }
}

type XMLObject = { [key in string]: XMLParsable | XMLObject | Array<XMLObject> } & { value?: XMLParsable };
type XMLParsable = string | number | boolean;

function isProp(
  props: [string, XMLObject | XMLParsable | Array<XMLObject>],
): props is [key: string, value: XMLParsable] {
  return !isChild(props);
}
function isChild(
  props: [string, XMLObject | XMLParsable | Array<XMLObject>],
): props is [key: string, value: XMLObject | Array<XMLObject>] {
  return props[0] === 'value' || ((props[1] instanceof Array || typeof props[1] === 'object') && props[1] !== null);
}

function sanitize(str: string) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}
